# Project: Web
# Path: .github/workflows/cd.yaml
# Description: Continuous Deployment workflow for Web

name: Continuous Deployment

on:
  push:
    branches: [main]

env:
  ENVIRONMENT: staging
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SHA: ${{ github.sha }}
  WEB_PORT: 3000
  NAMESPACE_CHART_VERSION: 0.1.0
  DEPLOYMENT_CHART_VERSION: 0.1.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOMAIN: staging.m-oo-r.com
      KRATOS_SERVICE_URL: ${{ secrets.KRATOS_SERVICE_URL }}
      KRATOS_SERVICE_ADMIN_URL: ${{ secrets.KRATOS_SERVICE_ADMIN_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install envsubst
        run: sudo apt-get install -y gettext-base

      - name: Process Dockerfile
        run: |
          envsubst < Dockerfile > Dockerfile_processed
          mv Dockerfile_processed Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push image with multi-platform support
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64  # Specify platforms
          tags: gcr.io/${{ secrets.PROJECT_ID }}/images/web/staging:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
  
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: ${{ secrets.REGION }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.REGION }} --project ${PROJECT_ID}

      - name: Install envsubst
        run: sudo apt-get install -y gettext-base

      - name: Update Values configuration
        run: |
          envsubst < values.yml > values_processed.yml
          mv values_processed.yml values.yml

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Pull and Export Namespace Helm Chart from GCR
        run: |
          # Pull the chart from GCR
          helm pull oci://gcr.io/${{ secrets.PROJECT_ID }}/charts/namespace --version ${NAMESPACE_CHART_VERSION} --untar --untardir ./charts

      - name: Deploy Namespace with Helm
        run: |
          helm upgrade --install web-staging-namespace ./charts/namespace \
            -f values.yml \
            --version ${NAMESPACE_CHART_VERSION}

      - name: Pull and Export Deployment Helm Chart from GCR
        run: |
          # Pull the chart from GCR
          helm pull oci://gcr.io/${{ secrets.PROJECT_ID }}/charts/deployment --version ${DEPLOYMENT_CHART_VERSION} --untar --untardir ./charts

      - name: Deploy Deployment with Helm
        run: |
          helm upgrade --install web-staging ./charts/deployment \
            -n web-${ENVIRONMENT} \
            -f values.yml \
            --version ${DEPLOYMENT_CHART_VERSION}
